name: crab_farm_monitor_desktop
description: CrabFarm Monitor - Desktop aquaculture monitoring app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  fl_chart: ^0.70.2
  flutter_dotenv: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/logo.png
    - assets/images/background_light.png
    - assets/images/background_dark.png
    - assets/images/ai_assistant_mascot.png
